name: deploy

on:
  push:
    paths:
      - 'public/**'
      - 'src/**'
      - '**.json'
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v1
      - name: Setup NodeJs
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install Dependencies
        run: npm install
      - name: Run test
        run: npm test
      # - name: deploy
